### PR TITLE
#9, #10, Major rewrite ;)

### PR DESCRIPTION
**Pull request by koscejev**
Hey, after delving deeply into intricacies of sub-optimal spring support in RESTeasy I kind of ended up taking a different approach to the whole thing: customizing `SpringBeanProcessor` instead of everything else. In my opinion this ends up being a much easier solution. 

Of course that would mean that 3.0.17.Final version of RESTEasy doesn't have those changes yet and these changes are not as easy to transfer there. (But not impossible either - perhaps ending up with two different `SpringBeanProcessor`s available.)

Unfortunately I didn't fully understand the complicated logic around creating `ServletBeanRegistration`, so I ended up making a simple one only. The same also happened with some unit tests, so I ended up adopting integration tests using RestAssured I am more familiar with. Please feel free to take only the parts you like from my efforts. (Actually only one module should have integration tests, the other one's should be deleted, I think.)

The usage is also different: only one JAX-RS `Application` bean can be registered with Spring context. I couldn't figure out how it would be possible to support multiple, separating different resources for different applications. (I have a feeling that it didn't work anyway.) And it seems `JerseyAutoConfiguration`, which inspired this change, also doesn't support multiple Applications. (Jersey actually requires their custom subclass `ResourceConfig`).

This solves #9 and #10.

Commit notes below:
* ResteasyAutoConfiguration somewhat similar to JerseyAutoConfiguration
* ResteasyProperties to get init params from application.properties with prefix "spring.resteasy"
* ResteasyDeploymentConfiguration as ConfigurationBootstrap that simply reads these properties instead of servlet init params
* CustomSpringBeanProcessor with a bunch of code removed to avoid dependency on Deployment and Registry
* unit tests replaced with integration tests, although more tests are definitely needed :/
* .editorconfig cause it's awesome

### CODE REVIEW

**Comment by fabiocarvalho777** [comment]
Thanks @koscejev . I will take a better look at it. The main idea is to make sure all use cases that used to work before this change, still work the same if this PR is merged. Also, I don't think sending another PR to RESTEasy (to accommodate this new architecture) is a good idea, that should be avoided, especially because they already merged the first PR that was sent to align with this starter. In the other hand, it is pretty cool that you could provide this PR so quickly, and we very likely will use at least pieces 
of it, like you mentioned.
So, let's keep the conversation in this PR.
Thanks a lot, I appreciate it.

**Comment by koscejev** [comment]
Great. So here are my reasons for redesign (customizing the `BeanFactoryPostProcessor` instead of Listener/Dispatcher/Registry):

1. The changes are actually simplifications, not additions. (Customized parts are mostly about deleting stuff, not adding stuff.) And there are fewer classes. ;)

2. It more closely follows the Spring flow, which is not just nice, but also a necessity:
  * Fewer beans are created before the `BeanFactoryPostProcessor` is initialized, which is good, as more beans can be easily customized by final application.
  * As most beans are created after the `BeanFactoryPostProcessor`, these beans have access to things such as properties, which is crucial for #10. Without this, it would've been necessary to read those properties in a more involved way, instead of using spring-boot's streamlined annotation solution.

3. The removed parts (such as registering `Deployment`, `ProviderFactory` and `Registry` with Spring) didn't have to be in the `BeanFactoryPostProcessor`. To be honest, I consider it a design flaw, where one class is trying to be responsible for too much, breaking the single responsibility principle. Even their original resteasy-spring integration contains application context xml that could've simply registered those.

4. This approach doesn't actually change which beans are created.

  * Example: Deployment might still initialize asynchronous dispatcher and is not forced to use synchronous. (Although I haven't yet read into what this actually affects.) 
  * And it can probably be developed a bit further to even support custom `ProviderFactory` bean by having own hidden `ProviderFactory`, then switching to any `ProviderFactory` found as a registered application bean and copying over all changes accumulated until that point. That would allow customizing `ProviderFactory` bean too, for maximum customization!

Either way, the original version you created provided a great starting point for my investigations, trying to get my approach to work. Furthermore, I probably won't try to publish my versions separately, because besides creating this code, there's a lot of other work, such as releasing maven version and publishing it to maven repository, contacting spring-boot team to mention it in their lists, etc.

I understand RESTEasy team already merged the other PR. That PR contained changes that made sense (improved RESTEasy design) even without spring-boot-starter. In my opinion, my proposed changes would also improve design (see point 3 above). If you end up agreeing with this approach, I'll try to find time and create PR for RESTEasy as well. It will need some cleanup, though, as it should support their use case too: enabling servlet-spring-resteasy integration by simply importing prepared spring context xml with multiple beans.

**Comment by fabiocarvalho777** [comment]
Thanks.
I will review it carefully soon, hopefully by the end of this week.

**Comment by fabiocarvalho777** [comment]
Hello,

Would you mind please decoupling this PR and different PRs? See below.

1. Please, send a separated PR with only functional tests addition (but not removing the unit tests)
1. Send another PR with only the .editorconfig addition.

Regarding the major refactor commits, I am not sure they will be merged, RESTEasy 3.0.17 is about to be released, then a new RESTEasy Spring Boot starter release will follow that, removing those 3 custom classes. Will that address your needs? Notice also that I have released version 2.0.0 already. See the release notes.

Thanks.

**Comment by koscejev** [comment]
Hi, I'll see if I can find some time for this. However, since we're already using version outlined in this PR, it's no longer a priority for us, so it might not be soon. Feel free to close this, if necessary.

**Pull request closed without merging**
