### PR TITLE
[40] Compatibility with Spring 4.1

### PR DESCRIPTION
**Pull request by janzak**
Replacing Import annotation with Beans annotated methods

### CODE REVIEW

**Comment by fabiocarvalho777** [comment]
Hi Janzak. A few points here:

1. In your PR you forgot to remove the @Component from one those two classes. Please, go ahead and fix that in your PR (squash your second commit please).
1. The CI build for your PR failed. Would you mind checking that too? I can't merge it if the CI build doesn't pass.
1. This project was reviewed by Spring and Spring Boot framework teams and using that @Import annotation was actually something they recommended.

Please take care of the issues I mentioned, and let me think about this case a little better and then I will respond. But thanks a lot for reaching me, your feedback and your PR.

**Comment by janzak** [comment]
Hi Fabio,

please, let me comment on the issues you mentioned:

1) Done.

2) The CI build seems to be failing due to some issues with the CI infrastructure (most likely unrelated to my PR):
$ java -jar jpm4j.jar --user init
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at aQute.jpm.main.Main.<clinit>(Main.java:74)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

As I'm not familiar with Travis CI and your CI setup, I cannot help you out in this regard unfortunately.

3) I believe that Spring guys are recommending using the Import annotation to directly refer to a Spring component in Spring 4.2. However, in Spring 4.1 they actively rejected this configuration construct and threw an exception when they came across it. The rule has been relaxed since then but for those of us who are for this or that reason stuck with 4.1 it would be great if resteasy-spring-boot used constructs compatible with both versions. This is basically the rationale behind my PR.

Thanks and best regards,
Jan

**Comment by fabiocarvalho777** [comment]
Thanks @janzak . I will test and merge it in a few days.

**Comment by fabiocarvalho777** [comment]
Hey, I just noticed you pushed this PR against the master branch. Would you please push it to develop branch instead?

**Comment by janzak** [comment]
I've changed the base branch of this PR.

**Pull request merged**
